# 패턴 적용

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
---
jwt:
  secret:
    key: sWjaoxj8s2$9f86jcnsi$2W9d3fPS02
---
# MYSQL JaeYoung TEST. OK.
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jelog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: qwe123
  jpa:
    show-sql: false # 로그출력
    hibernate:
      format_sql: false # 로그출력
      ddl-auto: create # none , create
      defer-datasource-initialization: false # dummy data
    logging:    # 로깅
      level:
        org:
#          springframework: DEBUG
          hibernate:
            Connection:
              charSet: UTF-8
            SQL: DEBUG
            type:
              false
    sql:                                  # dummy data
      init:
        mode: always
---